"""The Session path on AWS: four Lambda container images behind function URLs.

Why Lambda and not App Runner: AWS closed App Runner to new customers in 2026,
so a participant with a fresh account cannot create one. AWS points at ECS
Express Mode (Fargate plus a load balancer, always warm, an idle cost); Lambda
is the serverless analogue of the GCP track's Cloud Run: scale to zero, pay per
request, one image, and the cold start is something to measure rather than hide.
The Lambda Web Adapter in the image lets the same uvicorn process serve.

Each function has its own execution role. Only the policy and agent functions
may invoke models, and only the three course models. The API key lives in
Secrets Manager and is read once at cold start by the role that owns it.
"""

from __future__ import annotations

from aws_cdk import CfnOutput, Duration, RemovalPolicy, Size, Stack
from aws_cdk import aws_cloudwatch as cw
from aws_cdk import aws_cloudwatch_actions as cw_actions
from aws_cdk import aws_ecr_assets as ecr_assets
from aws_cdk import aws_iam as iam
from aws_cdk import aws_lambda as lam
from aws_cdk import aws_logs as logs
from aws_cdk import aws_secretsmanager as sm
from constructs import Construct

from stacks.common import (
    MODEL_IDS,
    REPO_ROOT,
    SERVICES,
    alerts_topic,
    bedrock_invoke_policy,
    monthly_budget,
)

# memory in MB and timeout in seconds per service; Lambda allocates CPU with memory.
SIZING = {"triage": (2048, 60), "semantic": (4096, 90), "policy": (4096, 120), "agent": (8192, 300)}


class SessionPath(Construct):
    def __init__(
        self, scope: Construct, id: str, *, region: str, budget_usd: float, alert_email: str | None
    ) -> None:
        super().__init__(scope, id)
        topic = alerts_topic(self, alert_email)
        self.functions: dict[str, lam.DockerImageFunction] = {}
        self.urls: dict[str, str] = {}

        # One API key for the cohort's services. Generated by Secrets Manager, never in an
        # image or a repo; `aws secretsmanager get-secret-value` prints it for the curl steps.
        self.api_key = sm.Secret(
            self,
            "ApiKey",
            description="northwind service API key",
            generate_secret_string=sm.SecretStringGenerator(
                exclude_punctuation=True, password_length=40
            ),
            removal_policy=RemovalPolicy.DESTROY,
        )

        for name, (app, artifacts, hf, _cpu, _mem) in SERVICES.items():
            memory, timeout = SIZING[name]
            role = iam.Role(
                self,
                f"Role{name.title()}",
                assumed_by=iam.ServicePrincipal("lambda.amazonaws.com"),
                description=f"northwind {name} execution role",
                managed_policies=[
                    iam.ManagedPolicy.from_aws_managed_policy_name(
                        "service-role/AWSLambdaBasicExecutionRole"
                    ),
                    # The documented policy for sending spans to the X-Ray OTLP endpoint.
                    iam.ManagedPolicy.from_aws_managed_policy_name("AWSXrayWriteOnlyPolicy"),
                ],
            )
            if name in ("policy", "agent"):
                role.add_to_policy(bedrock_invoke_policy(self))
            self.api_key.grant_read(role)
            env = {
                "NW_TRACK": "aws",
                "NW_AWS_REGION": region,
                "NW_LOG_FORMAT": "json",
                "NW_API_KEY_SECRET_ARN": self.api_key.secret_arn,
                "NW_TRACE_EXPORT": "xray",
                # The capstone sends 20 tickets through the loop and 20 through the router;
                # the cap stops a runaway loop before the budget alarm can.
                "NW_SPEND_CAP_USD": "25",
                "OTEL_SERVICE_NAME": f"northwind-{name}",
                "NW_TRACE_DIR": "/tmp/traces",
                "HF_HOME": "/app/hf",
            }
            if name == "agent":
                env["NW_AGENT_ROLE"] = "resolver"
            fn = lam.DockerImageFunction(
                self,
                f"Fn{name.title()}",
                function_name=f"northwind-{name}",
                code=lam.DockerImageCode.from_image_asset(
                    directory=str(REPO_ROOT),
                    file="Dockerfile",
                    platform=ecr_assets.Platform.LINUX_ARM64,
                    build_args={
                        "APP": app,
                        "ARTIFACTS": artifacts,
                        "HF_MODELS": hf,
                        "LAMBDA": "1",
                        "PORT": "8000",
                    },
                    exclude=[
                        ".venv",
                        ".git",
                        "tests",
                        "notebooks",
                        "docs",
                        "deploy",
                        "data/tickets.jsonl",
                        "data/policies",
                        "data/golden",
                    ],
                ),
                architecture=lam.Architecture.ARM_64,
                memory_size=memory,
                timeout=Duration.seconds(timeout),
                ephemeral_storage_size=Size.mebibytes(1024),
                role=role,
                environment=env,
                tracing=lam.Tracing.ACTIVE,
                log_group=logs.LogGroup(
                    self,
                    f"Logs{name.title()}",
                    log_group_name=f"/aws/lambda/northwind-{name}",
                    retention=logs.RetentionDays.ONE_MONTH,
                    removal_policy=RemovalPolicy.DESTROY,
                ),
                description=f"northwind {name} service",
            )
            url = fn.add_function_url(auth_type=lam.FunctionUrlAuthType.NONE)
            self.functions[name] = fn
            self.urls[name] = url.url
            # Outputs are read by the guide with jq as `.["northwind-session"].UrlAgent`, so the
            # logical id is pinned; without this CDK prefixes the construct path (SessionUrlAgent...).
            CfnOutput(self, f"Url{name.title()}", value=url.url).override_logical_id(
                f"Url{name.title()}"
            )
            self._alarms(name, fn, topic)
        self._dashboard()
        monthly_budget(self, limit_usd=budget_usd, email=alert_email)
        CfnOutput(self, "ApiKeySecretArn", value=self.api_key.secret_arn).override_logical_id(
            "ApiKeySecretArn"
        )

    def _alarms(self, name: str, fn: lam.Function, topic) -> None:
        errors = cw.Alarm(
            self,
            f"AlarmErrors{name}",
            metric=fn.metric_errors(period=Duration.minutes(5), statistic="Sum"),
            threshold=5,
            evaluation_periods=2,
            alarm_description=f"northwind-{name}: more than 5 errors in 5 minutes, twice",
            treat_missing_data=cw.TreatMissingData.NOT_BREACHING,
        )
        latency = cw.Alarm(
            self,
            f"AlarmLatency{name}",
            metric=fn.metric_duration(period=Duration.minutes(5), statistic="p95"),
            threshold=8000,
            evaluation_periods=3,
            alarm_description=f"northwind-{name}: p95 duration above 8 seconds for 15 minutes",
            treat_missing_data=cw.TreatMissingData.NOT_BREACHING,
        )
        for a in (errors, latency):
            a.add_alarm_action(cw_actions.SnsAction(topic))

    def _dashboard(self) -> None:
        board = cw.Dashboard(self, "Dashboard", dashboard_name="northwind")
        for name, fn in self.functions.items():
            board.add_widgets(
                cw.GraphWidget(
                    title=f"{name} invocations and errors",
                    left=[
                        fn.metric_invocations(statistic="Sum"),
                        fn.metric_errors(statistic="Sum"),
                    ],
                ),
                cw.GraphWidget(
                    title=f"{name} duration p50 p95",
                    left=[fn.metric_duration(statistic="p50"), fn.metric_duration(statistic="p95")],
                ),
            )

        # AWS/Bedrock publishes per model: without the ModelId dimension the panel stays empty.
        def bedrock(metric: str) -> list[cw.Metric]:
            return [
                cw.Metric(
                    namespace="AWS/Bedrock",
                    metric_name=metric,
                    statistic="Sum",
                    dimensions_map={"ModelId": model_id},
                    label=f"{metric} {role}",
                )
                for role, model_id in MODEL_IDS.items()
            ]

        board.add_widgets(
            cw.GraphWidget(
                title="Bedrock tokens per model",
                left=bedrock("InputTokenCount") + bedrock("OutputTokenCount"),
            ),
            cw.GraphWidget(
                title="Bedrock invocations and throttles per model",
                left=bedrock("Invocations") + bedrock("InvocationThrottles"),
            ),
        )


class SessionStack(Stack):
    def __init__(
        self, scope: Construct, id: str, *, budget_usd: float, alert_email: str | None, **kw
    ) -> None:
        super().__init__(scope, id, **kw)
        self.path = SessionPath(
            self, "Session", region=self.region, budget_usd=budget_usd, alert_email=alert_email
        )
