"""The Session path on AWS: four Lambda container images behind function URLs.

Why Lambda and not App Runner: AWS closed App Runner to new customers in 2026,
so a participant with a fresh account cannot create one. AWS points at ECS
Express Mode (Fargate plus a load balancer, always warm, an idle cost); Lambda
is the serverless analogue of the GCP track's Cloud Run: scale to zero, pay per
request, one image, and the cold start is something to measure rather than hide.
The Lambda Web Adapter in the image lets the same uvicorn process serve.

Each function has its own execution role. Only the policy and agent functions
may invoke models, and only the three course models. The API key lives in
Secrets Manager and is read once at cold start by the role that owns it.

Progressive delivery: every function publishes a version, the alias `live` points
at it, and the function URL targets the alias. A CodeDeploy deployment group per
function moves the alias: 10 percent of traffic to the new version for 15 minutes,
then the rest, and back on its own if the function's errors or p95 alarm fires.
One configuration for all four, and a slow one, because the errors alarm needs
more than five errors in each of two consecutive five-minute periods before it
enters ALARM: a linear shift that finishes in ten minutes, or a canary held for
five, would end before the alarm could fire and nothing would roll back.
`cdk deploy` goes through the same shift (the alias carries a
CodeDeployLambdaAliasUpdate policy), so a code change takes 15 minutes to reach
all traffic; `scripts/deploy_aws.sh rollout <service>` starts one from the CLI.

Metrics: each function writes an Embedded Metric Format line every minute of
activity (`nw/metrics_export.py`, `NW_METRICS_FORMAT=emf`), which CloudWatch
Logs turns into the `Northwind` namespace with the dimensions Service and Stage.

Stages: `-c stage=<word>` puts the word after `northwind` in every name so dev,
staging and prod can share one account; with no stage the names are the ones the
guide uses.
"""

from __future__ import annotations

from aws_cdk import CfnOutput, Duration, RemovalPolicy, Size, Stack
from aws_cdk import aws_cloudwatch as cw
from aws_cdk import aws_cloudwatch_actions as cw_actions
from aws_cdk import aws_codedeploy as cd
from aws_cdk import aws_ecr_assets as ecr_assets
from aws_cdk import aws_iam as iam
from aws_cdk import aws_lambda as lam
from aws_cdk import aws_logs as logs
from aws_cdk import aws_secretsmanager as sm
from constructs import Construct

from stacks.common import (
    MODEL_IDS,
    REPO_ROOT,
    SERVICES,
    alerts_topic,
    bedrock_invoke_policy,
    check_stage,
    monthly_budget,
    prefix,
)

# memory in MB and timeout in seconds per service; Lambda allocates CPU with memory.
SIZING = {"triage": (2048, 60), "semantic": (4096, 90), "policy": (4096, 120), "agent": (8192, 300)}
DEPLOYMENT_CONFIG = cd.LambdaDeploymentConfig.CANARY_10_PERCENT_15_MINUTES
# The fields nw/metrics_export.py exports, as CloudWatch shows them.
EXPORTED = {"requests": "Requests", "errors": "Errors", "p95": "LatencyP95Ms", "cost": "CostUsd"}


class SessionPath(Construct):
    def __init__(
        self,
        scope: Construct,
        id: str,
        *,
        region: str,
        budget_usd: float,
        alert_email: str | None,
        stage: str = "",
    ) -> None:
        super().__init__(scope, id)
        self.stage = check_stage(stage)
        self.prefix = prefix(stage)
        topic = alerts_topic(self, alert_email, stage=stage)
        self.functions: dict[str, lam.DockerImageFunction] = {}
        self.aliases: dict[str, lam.Alias] = {}
        self.urls: dict[str, str] = {}

        # One API key for the cohort's services. Generated by Secrets Manager, never in an
        # image or a repo; `aws secretsmanager get-secret-value` prints it for the curl steps.
        # No fixed name: CloudFormation's generated name carries the stack name (and so the
        # stage), and a fixed name would collide with a secret still in its recovery window
        # after a same-day destroy and redeploy.
        self.api_key = sm.Secret(
            self,
            "ApiKey",
            description=f"{self.prefix} service API key",
            generate_secret_string=sm.SecretStringGenerator(
                exclude_punctuation=True, password_length=40
            ),
            removal_policy=RemovalPolicy.DESTROY,
        )
        deploy_app = cd.LambdaApplication(self, "Deploy", application_name=f"{self.prefix}-lambda")

        for name, (app, artifacts, hf, _cpu, _mem) in SERVICES.items():
            memory, timeout = SIZING[name]
            fn_name = f"{self.prefix}-{name}"
            role = iam.Role(
                self,
                f"Role{name.title()}",
                assumed_by=iam.ServicePrincipal("lambda.amazonaws.com"),
                description=f"{fn_name} execution role",
                managed_policies=[
                    iam.ManagedPolicy.from_aws_managed_policy_name(
                        "service-role/AWSLambdaBasicExecutionRole"
                    ),
                    # The documented policy for sending spans to the X-Ray OTLP endpoint.
                    iam.ManagedPolicy.from_aws_managed_policy_name("AWSXrayWriteOnlyPolicy"),
                ],
            )
            if name in ("policy", "agent"):
                role.add_to_policy(bedrock_invoke_policy(self))
            self.api_key.grant_read(role)
            env = {
                "NW_TRACK": "aws",
                "NW_AWS_REGION": region,
                "NW_LOG_FORMAT": "json",
                "NW_API_KEY_SECRET_ARN": self.api_key.secret_arn,
                "NW_TRACE_EXPORT": "xray",
                # One EMF line per minute of activity; CloudWatch Logs makes the metrics.
                "NW_METRICS_FORMAT": "emf",
                "NW_STAGE": self.stage,
                # The capstone sends 20 tickets through the loop and 20 through the router;
                # the cap stops a runaway loop before the budget alarm can.
                "NW_SPEND_CAP_USD": "25",
                "OTEL_SERVICE_NAME": fn_name,
                "NW_TRACE_DIR": "/tmp/traces",
                "HF_HOME": "/app/hf",
            }
            if name == "agent":
                env["NW_AGENT_ROLE"] = "resolver"
            fn = lam.DockerImageFunction(
                self,
                f"Fn{name.title()}",
                function_name=fn_name,
                code=lam.DockerImageCode.from_image_asset(
                    directory=str(REPO_ROOT),
                    file="Dockerfile",
                    platform=ecr_assets.Platform.LINUX_ARM64,
                    build_args={
                        "APP": app,
                        "ARTIFACTS": artifacts,
                        "HF_MODELS": hf,
                        "LAMBDA": "1",
                        "PORT": "8000",
                    },
                    exclude=[
                        ".venv",
                        ".git",
                        "tests",
                        "notebooks",
                        "docs",
                        "deploy",
                        "data/tickets.jsonl",
                        "data/policies",
                        "data/golden",
                    ],
                ),
                architecture=lam.Architecture.ARM_64,
                memory_size=memory,
                timeout=Duration.seconds(timeout),
                ephemeral_storage_size=Size.mebibytes(1024),
                role=role,
                environment=env,
                tracing=lam.Tracing.ACTIVE,
                log_group=logs.LogGroup(
                    self,
                    f"Logs{name.title()}",
                    log_group_name=f"/aws/lambda/{fn_name}",
                    retention=logs.RetentionDays.ONE_MONTH,
                    removal_policy=RemovalPolicy.DESTROY,
                ),
                description=f"{fn_name} service",
            )
            # A published version per configuration (image digest, environment, memory):
            # the logical id of the version changes with the configuration, so every
            # deploy that changes the function publishes a new one.
            alias = lam.Alias(
                self, f"Alias{name.title()}", alias_name="live", version=fn.current_version
            )
            url = alias.add_function_url(auth_type=lam.FunctionUrlAuthType.NONE)
            self.functions[name] = fn
            self.aliases[name] = alias
            self.urls[name] = url.url
            # Outputs are read by the guide with jq as `.["northwind-session"].UrlAgent`, so the
            # logical id is pinned; without this CDK prefixes the construct path (SessionUrlAgent...).
            CfnOutput(self, f"Url{name.title()}", value=url.url).override_logical_id(
                f"Url{name.title()}"
            )
            errors, latency = self._alarms(name, fn, topic)
            self._drift_alarm(name, fn, topic)
            cd.LambdaDeploymentGroup(
                self,
                f"Deploy{name.title()}",
                application=deploy_app,
                deployment_group_name=fn_name,
                alias=alias,
                deployment_config=DEPLOYMENT_CONFIG,
                alarms=[errors, latency],
                auto_rollback=cd.AutoRollbackConfig(
                    failed_deployment=True, stopped_deployment=True, deployment_in_alarm=True
                ),
            )
        self._dashboard()
        monthly_budget(self, limit_usd=budget_usd, email=alert_email, stage=stage)
        CfnOutput(self, "ApiKeySecretArn", value=self.api_key.secret_arn).override_logical_id(
            "ApiKeySecretArn"
        )
        CfnOutput(self, "Stage", value=self.stage or "default").override_logical_id("Stage")
        CfnOutput(self, "DeployApplication", value=deploy_app.application_name).override_logical_id(
            "DeployApplication"
        )

    def _alarms(self, name: str, fn: lam.Function, topic) -> tuple[cw.Alarm, cw.Alarm]:
        """Errors and p95 duration per function: the pager and CodeDeploy's rollback trigger."""
        fn_name = f"{self.prefix}-{name}"
        errors = cw.Alarm(
            self,
            f"AlarmErrors{name}",
            alarm_name=f"{fn_name}-errors",
            metric=fn.metric_errors(period=Duration.minutes(5), statistic="Sum"),
            threshold=5,
            evaluation_periods=2,
            alarm_description=f"{fn_name}: more than 5 errors in 5 minutes, twice",
            treat_missing_data=cw.TreatMissingData.NOT_BREACHING,
        )
        latency = cw.Alarm(
            self,
            f"AlarmLatency{name}",
            alarm_name=f"{fn_name}-p95",
            metric=fn.metric_duration(period=Duration.minutes(5), statistic="p95"),
            threshold=8000,
            evaluation_periods=3,
            alarm_description=f"{fn_name}: p95 duration above 8 seconds for 15 minutes",
            treat_missing_data=cw.TreatMissingData.NOT_BREACHING,
        )
        for a in (errors, latency):
            a.add_alarm_action(cw_actions.SnsAction(topic))
        return errors, latency

    def _drift_alarm(self, name: str, fn: lam.Function, topic) -> None:
        """Every service logs `drift_alert` when its drift signal passes the bar (triage and
        semantic: input and prediction PSI; policy: retrieval confidence and refusal rate;
        agent: cap rate, tool errors, cost per run). A metric filter per function turns that
        line into a metric and the alarm pages on the first one."""
        fn_name = f"{self.prefix}-{name}"
        metric_name = f"DriftAlerts-{self.stage}-{name}" if self.stage else f"DriftAlerts-{name}"
        metric = logs.MetricFilter(
            self,
            f"DriftFilter{name.title()}",
            log_group=fn.log_group,
            metric_namespace="Northwind",
            metric_name=metric_name,
            filter_pattern=logs.FilterPattern.string_value("$.msg", "=", "drift_alert"),
            metric_value="1",
        ).metric(period=Duration.minutes(5), statistic="Sum")
        alarm = cw.Alarm(
            self,
            f"AlarmDrift{name.title()}",
            alarm_name=f"{fn_name}-drift",
            metric=metric,
            threshold=1,
            evaluation_periods=1,
            alarm_description=f"{fn_name}: drift signal past its bar",
            treat_missing_data=cw.TreatMissingData.NOT_BREACHING,
        )
        alarm.add_alarm_action(cw_actions.SnsAction(topic))
        self.drift_metrics = getattr(self, "drift_metrics", []) + [metric]

    def _exported(self, name: str, metric: str, statistic: str) -> cw.Metric:
        """A series the service itself exported through its EMF line."""
        return cw.Metric(
            namespace="Northwind",
            metric_name=metric,
            dimensions_map={"Service": name, "Stage": self.stage or "default"},
            statistic=statistic,
            period=Duration.minutes(1),
            label=f"{name} {metric}",
        )

    def _dashboard(self) -> None:
        board = cw.Dashboard(self, "Dashboard", dashboard_name=self.prefix)
        # Per function: what Lambda saw (invocations include the init failures the service
        # never sees) next to what the service measured (its own request histogram).
        for name, fn in self.functions.items():
            board.add_widgets(
                cw.GraphWidget(
                    title=f"{name} invocations and errors (Lambda)",
                    left=[
                        fn.metric_invocations(statistic="Sum"),
                        fn.metric_errors(statistic="Sum"),
                    ],
                ),
                cw.GraphWidget(
                    title=f"{name} duration p50 p95 (Lambda, includes init)",
                    left=[fn.metric_duration(statistic="p50"), fn.metric_duration(statistic="p95")],
                ),
                cw.GraphWidget(
                    title=f"{name} requests and errors (exported)",
                    left=[
                        self._exported(name, EXPORTED["requests"], "Sum"),
                        self._exported(name, EXPORTED["errors"], "Sum"),
                    ],
                ),
                cw.GraphWidget(
                    title=f"{name} p95 latency ms (exported)",
                    left=[self._exported(name, EXPORTED["p95"], "Maximum")],
                ),
            )

        board.add_widgets(
            cw.GraphWidget(
                title="model cost per minute, USD (exported)",
                left=[self._exported(n, EXPORTED["cost"], "Sum") for n in ("policy", "agent")],
            ),
            cw.GraphWidget(
                title="drift level per service (exported: 0 ok, 1 watch, 2 alert)",
                left=[self._exported(n, "DriftLevel", "Maximum") for n in self.functions],
            ),
        )
        if getattr(self, "drift_metrics", None):
            board.add_widgets(
                cw.GraphWidget(title="drift alerts per service", left=self.drift_metrics)
            )

        # AWS/Bedrock publishes per model: without the ModelId dimension the panel stays empty.
        def bedrock(metric: str) -> list[cw.Metric]:
            return [
                cw.Metric(
                    namespace="AWS/Bedrock",
                    metric_name=metric,
                    statistic="Sum",
                    dimensions_map={"ModelId": model_id},
                    label=f"{metric} {role}",
                )
                for role, model_id in MODEL_IDS.items()
            ]

        board.add_widgets(
            cw.GraphWidget(
                title="Bedrock tokens per model",
                left=bedrock("InputTokenCount") + bedrock("OutputTokenCount"),
            ),
            cw.GraphWidget(
                title="Bedrock invocations and throttles per model",
                left=bedrock("Invocations") + bedrock("InvocationThrottles"),
            ),
        )


class SessionStack(Stack):
    def __init__(
        self,
        scope: Construct,
        id: str,
        *,
        budget_usd: float,
        alert_email: str | None,
        stage: str = "",
        **kw,
    ) -> None:
        super().__init__(scope, id, **kw)
        self.path = SessionPath(
            self,
            "Session",
            region=self.region,
            budget_usd=budget_usd,
            alert_email=alert_email,
            stage=stage,
        )
